/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_winning_hic_base_utils_JniBase64Convert */

#ifndef _Included_com_winning_hic_base_utils_JniBase64Convert
#define _Included_com_winning_hic_base_utils_JniBase64Convert
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_winning_hic_base_utils_JniBase64Convert
 * Method:    zipEmrXml
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_winning_hic_base_utils_JniBase64Convert_zipEmrXml
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_winning_hic_base_utils_JniBase64Convert
 * Method:    unzipEmrXml
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_winning_hic_base_utils_JniBase64Convert_unzipEmrXml
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
