----首次病程
UPDATE A SET A.sjysbm =C.ZRYSDM,A.sjysqm=C.ZRYSXM
FROM CISDB_DATA..HLHT_ZYBCJL_SCBCJL A,CISDB..CPOE_BRSYK C
WHERE A.jzlsh=C.SYXH AND (A.sjysbm ='N' OR A.sjysqm ='N' )

UPDATE CISDB_DATA..HLHT_ZYBCJL_SCBCJL SET zyszgcjg='无' WHERE CONVERT(varchar,zyszgcjg) ='N'
UPDATE CISDB_DATA..HLHT_ZYBCJL_SCBCJL SET zdyjdm=NULL WHERE zdyjdm='N'
UPDATE CISDB_DATA..HLHT_ZYBCJL_SCBCJL SET czzybmdm=NULL WHERE czzybmdm='N'
UPDATE CISDB_DATA..HLHT_ZYBCJL_SCBCJL SET czzybm=NULL WHERE czzybm='N'
UPDATE CISDB_DATA..HLHT_ZYBCJL_SCBCJL SET czzyzhdm=NULL WHERE czzyzhdm='N'
UPDATE CISDB_DATA..HLHT_ZYBCJL_SCBCJL SET czzyzh=NULL WHERE czzyzh='N'
UPDATE CISDB_DATA..HLHT_ZYBCJL_SCBCJL SET jzzybmdm=NULL WHERE jzzybmdm='N'
UPDATE CISDB_DATA..HLHT_ZYBCJL_SCBCJL SET jzzybmmc=NULL WHERE jzzybmmc='N'
UPDATE CISDB_DATA..HLHT_ZYBCJL_SCBCJL SET jzzyzhbm=NULL WHERE jzzyzhbm='N'
UPDATE CISDB_DATA..HLHT_ZYBCJL_SCBCJL SET jzzyzhmc=NULL WHERE jzzyzhmc='N'
UPDATE CISDB_DATA..HLHT_ZYBCJL_SCBCJL SET zfbm='无' WHERE zfbm='N'
UPDATE CISDB_DATA..HLHT_ZYBCJL_SCBCJL SET zzzf='无' WHERE zzzf='N'